[project]
name = "zeler-fulldock"
version = "0.0.0"
description = "FullDock module package"
requires-python = ">=3.11"
dependencies = ["zeler_platform_core", "aio-pika>=9.4.0", "fastapi>=0.110,<1", "httpx>=0.27.0", "uvicorn[standard]>=0.30.0", "motor>=3.7.1"]

[build-system]
requires = ["hatchling>=1.24.0"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/zeler_fulldock"]

[tool.uv.sources]
zeler_platform_core = { workspace = true }
